baseURL: "https://purgty.github.io/Personal-Portfolio/"
languageCode: "en-us"
title: "Aswinkumar Varathakumaran"
theme: "PaperMod"

pagination:
  pagerSize: 20
enableRobotsTXT: true
enableInlineShortcodes: true

taxonomies:
  tag: tags

menu:
  main:
    # - name: Books
    #   url: books/
    #   weight: 5
    - name: Papers
      url: papers/
      weight: 2
    - name: Certifications
      url: courses/
      weight: 3
    # - name: Data
    #   url: data/
      # weight: 4
    # - name: Blog
    #   url: blog/
    #   weight: 6

params:
  description: "This website hosts Aswinkumar Varathakumaranâ€™s research papers, projects, books, course notes, datasets, CV, and contact information."
  author: "Aswinkumar Varathakumaran"

  # UI and appearance
  defaultTheme: "light"
  hideFooter: false
  disableThemeToggle: false
  disableScrollToTop: true
  disableSpecial1stPost: true
  disableAnchoredHeadings: true

  # Page info & enhancements
  ShowShareButtons: false
  ShowReadingTime: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  ShowWordCount: false
  math: true

  # Table of contents
  UseHugoToc: true
  TocOpen: true
  showtoc: false

  # Section definition
  MainSections: ["books", "courses", "papers", "data"]

  # Profile mode
  profileMode:
    enabled: true
    title: "Aswinkumar V"
    subtitle: "Senior Undergraduate Computer Science student passionate about Machine Learning, Computer Vision, and Generative AI."
    imageUrl: "potrait.jpeg"
    imageWidth: 160
    imageHeight: 160
    buttons:
      - name: Papers
        url: papers/
      # - name: Data
      #   url: data/
      # - name: Books
      #   url: books/
      - name: Certifications
        url: courses/
      - name: Tags
        url: tags/
      # - name: Archive
      #   url: archive/
      # - name: Blog
      #   url: blog/

  # Social icons
  socialIcons:
    - name: CV
      url: CV - Aswinkumar.pdf
    - name: GitHub
      url: "https://github.com/Purgty"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/aswinkumar-v-2a776a354/"

  # Branding
  label:
    text: "Aswinkumar Varathakumaran"
    icon: "organization_work_documents_portfolio_business_briefcase_icon_266342.ico"
    iconHeight: 18

  # Assets & covers
  assets:
    disableScrollBarStyle: true

  cover:
    hiddenInList: false
    hiddenInSingle: true

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    guessSyntax: true
    style: autumn

  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2